### ISSUE TITLE
MS Graph not pulling expected data

### ISSUE THREAD

**Issue by crazycga** [microsoftgraph/msgraph-sample-aspnet-core#130]
**Describe the bug**
I have a strange bug with this tutorial.  I followed it directly, but the ability to actually grab the Graph data appears to not be working properly.  There's no error message, it just doesn't grab my name or other information.

![image](https://github.com/microsoftgraph/msgraph-sample-aspnet-core/assets/22846280/67e62888-5367-4bd2-897c-16e01024cd33)

**To Reproduce**
1. Follow steps in tutorial README.md
2. Execute
3. See screenshot

**Expected behavior**
My name should be in there.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- Windows 10; using Edge InPrivate; Azure AD tenant is a client of mine.
- 
**Dependency versions**
I changed the package to .NET 6 for this particular example, but the behavior is identicial in .NET 7.

**Additional context**
I noted this in the stack trace, and it concerned me.  **According to one of my employees, this *worked as-is* a week and a half ago, too.**

The stack trace:
## my specific concerning line:
```
Microsoft.Identity.Web.TokenAcquisition: Information: [MsIdWeb] An error occured during token acquisition: No account or login hint was passed to the AcquireTokenSilent call. 
```

## Original:
```
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 61ffc6a0-e115-4ff6-acd6-f76f604bc411] TokenEndpoint: ****
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: Microsoft.IdentityModel Version: 6.33.0.0. Date 10/16/2023 15:37:27. PII logging is OFF. See https://aka.ms/IdentityModel/PII for details. 
IDX10242: Security token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]' has a valid signature.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10239: Lifetime of the token is valid.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10234: Audience Validated.Audience: 'd3969ae9-085c-4938-b0cb-234ba4533f3f'
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10245: Creating claims identity from the validated token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Information: IDX10241: Security token validated. token: '[PII of type 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] MSAL MSAL.NetCore with assembly version '4.56.0.0'. CorrelationId(43f2aab0-3f31-42a6-ad4e-94622d556ac5)
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] === AcquireTokenSilent Parameters ===
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] LoginHint provided: False
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] Account provided: False
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] ForceRefresh: False
Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] 
=== Request Data ===
Authority Provided? - True
Scopes - User.Read MailboxSettings.Read Calendars.ReadWrite
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 43f2aab0-3f31-42a6-ad4e-94622d556ac5
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

Microsoft.Identity.Web.TokenAcquisition: Information: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] === Token Acquisition (SilentRequest) started:
	 Scopes: User.Read MailboxSettings.Read Calendars.ReadWrite
	Authority Host: login.microsoftonline.com
Microsoft.Identity.Web.TokenAcquisition: Warning: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] Only in-memory caching is used. The cache is not persisted and will be lost if the machine is restarted. It also does not scale for a web app or web API, where the number of users can grow large. In production, web apps and web APIs should use distributed caching like Redis. See https://aka.ms/msal-net-cca-token-cache-serialization
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
'GraphTutorial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.23\System.Diagnostics.StackTrace.dll'. 
'GraphTutorial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.23\System.Reflection.Metadata.dll'. 
Microsoft.Identity.Web.TokenAcquisition: Error: False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.23 Microsoft Windows 10.0.19045 [2023-10-16 15:37:27Z - 43f2aab0-3f31-42a6-ad4e-94622d556ac5] Exception type: Microsoft.Identity.Client.MsalUiRequiredException
, ErrorCode: user_null
HTTP StatusCode 0
CorrelationId 

   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in Microsoft.Identity.Client.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Identity.Client.MsalUiRequiredException' in System.Private.CoreLib.dll
Microsoft.Identity.Web.TokenAcquisition: Information: [MsIdWeb] An error occured during token acquisition: No account or login hint was passed to the AcquireTokenSilent call. 

MSAL.NetCore.4.56.0.0.MsalUiRequiredException: 
	ErrorCode: user_null
Microsoft.Identity.Client.MsalUiRequiredException: No account or login hint was passed to the AcquireTokenSilent call. 
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForWebAppWithAccountFromCacheAsync(IConfidentialClientApplication application, ClaimsPrincipal claimsPrincipal, IEnumerable`1 scopes, String tenantId, MergedOptions mergedOptions, String userFlow, TokenAcquisitionOptions tokenAcquisitionOptions)
   at Microsoft.Identity.Web.TokenAcquisition.GetAuthenticationResultForUserAsync(IEnumerable`1 scopes, String authenticationScheme, String tenantId, String userFlow, ClaimsPrincipal user, TokenAcquisitionOptions tokenAcquisitionOptions)
	StatusCode: 0 
	ResponseBody:  
	Headers: 
Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in Microsoft.Identity.Web.TokenAcquisition.dll
Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in System.Net.Http.dll
Exception thrown: 'Microsoft.Identity.Web.MicrosoftIdentityWebChallengeUserException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Graph.ServiceException' in Microsoft.Graph.Core.dll
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.Graph.ServiceException' in System.Private.CoreLib.dll
GraphTutorial.Controllers.HomeController: Information: This just happened.
GraphTutorial.Controllers.HomeController: Information: User info: System.Security.Claims.ClaimsPrincipal
'GraphTutorial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.23\Microsoft.Extensions.Identity.Core.dll'. 
```

**Comment by crazycga** [comment]
Duplicate #129

**Comment by crazycga** [comment]
Confirmed that #129 is, in fact, the same issue.  This works when microsoft.identity.web[.*] is downgraded to 2.14.

**Comment by jasonjoh** [comment]
Thanks @crazycga for confirming! I'm keeping an eye on M.I.W for a fix, and will update the sample.
